# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Continuous Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 6'

jobs:
  beman-submodule-check:
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-submodule-check.yml@1.3.0

  build-and-test:
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-build-and-test.yml@1.3.0
    with:
      matrix_config: >
        {
          "gcc": [
            { "versions": ["trunk"],
              "tests": [
                { "cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libstdc++"],
                      "tests": ["Debug.-DCMAKE_CXX_FLAGS=-freflection"]
                    }
                  ]
                }
              ]
            }
          ],
          "clang-p2996": [
            { "versions": ["trunk"],
              "tests": [
                {"cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libc++"],
                      "tests": ["Debug.-DCMAKE_CXX_FLAGS='-freflection -fparameter-reflection -fexpansion-statements -freflection-latest'"]
                    }
                  ]
                }
              ]
            }
          ]
        }

  create-issue-when-fault:
    needs: [build-and-test]
    if: failure() && github.event_name == 'schedule'
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-create-issue-when-fault.yml@1.3.0
